name: "grafana-annotation-actions"
author: "Daniel O'Neill"
description: "Create Grafana annotations using Github Actions. Update the annotation end time after an Action is finished."

inputs:
  grafanaHost:
    description: 'Grafana Hostname'
    required: true
  grafanaToken:
    description: 'Grafana API token'
    required: true
  grafanaText:
    description: 'Text that will appear on the annotation. Newlines unsupported.'
    required: false
  grafanaDashboardID:
    description: 'Id. of the dashboard to add the annotation on. If not provided, will be global to all dashboards.'
    required: false
  grafanaPanelID:
    description: 'Id. of the panel to add the annotation on. If not provided, will be global to all panels.'
    required: false
  grafanaTags:
    description: 'JSON valid array of tags. EG: ["tag1", "tag2"]'
    required: false
  grafanaAnnotationID:
    description: 'Use this only to update the end time of a previously created annotation.'
    required: false

outputs:
  annotation-id:
    description: "The returned Grafana Annotation ID that can be used to set and end time to the annotation after an action has completed."

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'anchor'
  color: 'white'
